# Generated by Django 5.0.2 on 2024-03-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estados'),
        ),
    ]
